spring:
  application:
    name: learnify
  datasource:
    url: jdbc:postgresql://localhost:5432/learnify
    username: postgres
    password: vasko123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration