spring:
  application:
    name: learnify
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/learnify}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:vasko123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration