spring:
  application:
    name: learnify
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/learnify}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:vasko123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: ${JWT_ACCESS_EXPIRATION:300}
    refreshTokenExpiration: ${JWT_REFRESH_EXPIRATION:604800}